services:
  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abc123
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./data:/data/db
